### ISSUE TITLE
USER STORY: Publish a poll

### ISSUE THREAD

**Issue by Shida18719** [Shida18719/love-running#3]
In order **to collect user feedback**, as an administrator, I can **publish a poll.**

**Comment by Shida18719** [comment]
In order **to automatically hide a poll** as an administrator, I can **pick the expiry date** while publishing the poll.

# Acceptance Criteria:
* a. The poll should disappear at 11:59 PM on the targeted date.
* b. The real estate of the "Poll" should be reserved on the home page. A message that says "Stay Tuned, a new poll is coming soon" should appear if no other poll is active.
* c. The administrator expiry date should be at least 3 days after the current date.

## Tasks:
- [ ] Update the admin module view:  the poll design (HTML and CSS) to include date picker
- [ ] Update the website view:  show "Stay Tuned, a new website is coming soon"
- [ ] Create JavaScript function to validate the expiry date is at least after 3 days.
- [ ] Create a job to check expired Polls everyday at 11:59 PM and hide them 
- [ ]  Update the controller function
- [ ] Update the unit test script
- [ ] Test the functionality.
